id: application_user_login
schema_generating: true
display_name: application user login
document_category: application user login
weight: 20
fields:
- id: id
  description: A unique identifier for an entity. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: name
  description: A human-readable name for an attribute or entity.
  display_name: name
- id: enabled
  display_name: enabled
- id: archived
  display_name: archived
- id: description
  description: a human-readable description of an entity
  display_name: description
- id: note
  display_name: note
- id: category
  display_name: named thing_category
  cardinality: multi
- id: user_name
  display_name: user name
- id: domain_name
  display_name: domain name
