id: computational_process_or_activity
schema_generating: true
description: Either an individual operational activity, or a collection of causally
  connected operational activities
display_name: computational process or activity
document_category: computational process or activity
weight: 20
fields:
- id: id
  description: A unique identifier for an entity. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: name
  description: A human-readable name for an attribute or entity.
  display_name: name
- id: enabled
  display_name: enabled
- id: archived
  display_name: archived
- id: description
  description: a human-readable description of an entity
  display_name: description
- id: note
  display_name: note
- id: category
  display_name: named thing_category
  cardinality: multi
- id: has_input
  description: holds between a process and a continuant, where the continuant is an
    input into the process
  display_name: has input
  cardinality: multi
- id: has_output
  description: holds between a process and a continuant, where the continuant is an
    output of the process
  display_name: has output
  cardinality: multi
- id: enabled_by
  description: holds between a process and a cyber entity, where the cyber entity
    executes the process
  display_name: enabled by
  cardinality: multi
