id: operational_activity
schema_generating: true
description: An execution of a operational function carried out by a servicetype or
  macrooperational complex.
display_name: operational activity
document_category: operational activity
weight: 20
fields:
- id: id
  description: A unique identifier for an entity. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: name
  description: A human-readable name for an attribute or entity.
  display_name: name
- id: enabled
  display_name: enabled
- id: archived
  display_name: archived
- id: description
  description: a human-readable description of an entity
  display_name: description
- id: note
  display_name: note
- id: category
  display_name: named thing_category
  cardinality: multi
- id: has_input
  description: A orchestration entity that is the input for the reaction
  display_name: operational activity_has input
  cardinality: multi
- id: has_output
  description: A orchestration entity that is the output for the reaction
  display_name: operational activity_has output
  cardinality: multi
- id: enabled_by
  description: The servicetype, componentservice, or complex that catalyzes the reaction
  display_name: operational activity_enabled by
  cardinality: multi
