id: orchestration_exposure
schema_generating: true
description: A orchestration exposure is an intake of a particular control actor,
  other than a administrative operation.
display_name: orchestration exposure
document_category: orchestration exposure
weight: 20
fields:
- id: id
  description: A unique identifier for an entity. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: name
  description: A human-readable name for an attribute or entity.
  display_name: name
- id: enabled
  display_name: enabled
- id: archived
  display_name: archived
- id: description
  description: a human-readable description of an entity
  display_name: description
- id: note
  display_name: note
- id: category
  display_name: named thing_category
  cardinality: multi
- id: in_taxon
  description: connects an entity to its taxonomic classification. Only certain kinds
    of entities can be taxonomically classified; see 'thing with taxon'
  display_name: in taxon
  cardinality: multi
- id: timepoint
  description: a point in time
  display_name: timepoint
